// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RequirementAnalysisProject.Data;

#nullable disable

namespace RequirementAnalysisProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428114741_AddProjectIsolation")]
    partial class AddProjectIsolation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RequirementAnalysisProject.Models.Entities.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiSuggestions")
                        .HasColumnType("text");

                    b.Property<string>("Assumptions")
                        .HasColumnType("text");

                    b.Property<string>("BusinessRules")
                        .HasColumnType("text");

                    b.Property<string>("CommunicationGaps")
                        .HasColumnType("text");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DatabaseEntities")
                        .HasColumnType("text");

                    b.Property<string>("FunctionalRequirements")
                        .HasColumnType("text");

                    b.Property<string>("Modules")
                        .HasColumnType("text");

                    b.Property<string>("NonFunctionalRequirements")
                        .HasColumnType("text");

                    b.Property<string>("OpenQuestions")
                        .HasColumnType("text");

                    b.Property<string>("Prioritization")
                        .HasColumnType("text");

                    b.Property<string>("ProjectObjective")
                        .HasColumnType("text");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<string>("RiskFlags")
                        .HasColumnType("text");

                    b.Property<string>("Roles")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Completed");

                    b.Property<string>("SuggestedMilestones")
                        .HasColumnType("text");

                    b.Property<string>("UserStories")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("RequirementAnalysisProject.Models.Entities.ConsolidatedResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectObjective")
                        .HasColumnType("text");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("text");

                    b.Property<string>("ReportJson")
                        .HasColumnType("text");

                    b.Property<int>("TotalConversations")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ConsolidatedResults");
                });

            modelBuilder.Entity("RequirementAnalysisProject.Models.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("RequirementAnalysisProject.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("RequirementAnalysisProject.Models.Entities.AnalysisResult", b =>
                {
                    b.HasOne("RequirementAnalysisProject.Models.Entities.Conversation", "Conversation")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("RequirementAnalysisProject.Models.Entities.ConsolidatedResult", b =>
                {
                    b.HasOne("RequirementAnalysisProject.Models.Entities.Project", "Project")
                        .WithMany("ConsolidatedResults")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RequirementAnalysisProject.Models.Entities.Conversation", b =>
                {
                    b.HasOne("RequirementAnalysisProject.Models.Entities.Project", "Project")
                        .WithMany("Conversations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RequirementAnalysisProject.Models.Entities.Conversation", b =>
                {
                    b.Navigation("AnalysisResults");
                });

            modelBuilder.Entity("RequirementAnalysisProject.Models.Entities.Project", b =>
                {
                    b.Navigation("ConsolidatedResults");

                    b.Navigation("Conversations");
                });
#pragma warning restore 612, 618
        }
    }
}
